import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(GoodMorning()); //TO RUN THE APP
}

class GoodMorning extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _GoodMorningState();
  }
}

class _GoodMorningState extends State<GoodMorning> {
  var rng = new Random();
  List<Image> _myphoto = [
    Image.asset('ass/1.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/2.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/3.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/4.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/5.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/6.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/7.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/8.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/9.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/10.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/11.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/12.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/13.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/14.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/15.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/16.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/17.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/18.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/19.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/20.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/21.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/22.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/23.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/24.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/25.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/26.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
    Image.asset('ass/27.jpeg',
        alignment: Alignment.center, height: 500, width: 500),
  ];
  List<String> _product = [
    "My Sweet Moon",
    "Shining Star",
    "New Moon",
    "My Reason",
    "Cutie Pie",
    "Honey",
    "Hon",
    "Honey Bunch",
    "Candy",
    "Caramel",
    "Gummie Bear",
    "Gummy Bear",
    "Peaches",
    "Peach",
    "Peachy Pie",
    "Pumpkin",
    "Pumpkin pie",
    "Butter Cup",
    "Cherry",
    "Cookie",
    "Cookie Monster",
    "Sugar",
    "Sugar Lips"
    "Sugar Plum",
    "Sweetie",
    "Sweetheart",
    "Sweetness",
    "Sweet Heart",
    "Kit Kat",
    "Tootsie Roll",
    "Lolipop",
    "Fruit Loop",
    "Donut",
    "Monkey Muffins",
    "Cupcake",
    "Waffles",
    "Sprinkles",
    "Cuddle Cake",
    "Dumpling",
    "Sweet Butt",
    "Sweet Cakes",
    "Sweet Pea",
    "Sweetie Pie",
    "Sweetkins",
    "Sugar Smacks",
    "Snuggle Muffin",
    "Honey Bee",
    "Jellybean",
    "Love Muffin",
    "Yummy",
    "Toffee",
    "Marshymallow",
    "Marshmallow",
    "Skittle",
    "Almond Joy",
    "M&M",
    "Hershey’s",
    "Rolo",
    "Sweet Potato",
    "Snickers",
    "Twix",
    "Shortcake",
    "Brown Sugar",
    "Oreo",
    "Cream",
    "Eyecandy",
    "Cuddle Muffin",
    "Cinnamon",
    "Cinnamon Girl",
    "Blueberry Pie",
    "Sugar Mouse",
    "Sugar Sauce",
    "Tic Tac",
    "Candy Cane",
    "Sugar Bomb",
    "Pudding Pop",
    "Snuggle Pie",
    "Pooh",
    "Pooh Bear",
    "Giggles",
    "Bubbies",
    "Cuddly-Wuddly",
    "Cutie",
    "Cutie Head",
    "Cutie Pie",
    "Little Hummingbird",
    "Cutie Patootie",
    "Chipmunk",
    "Bunbuns",
    "Cuddles",
    "Cuddle Bug",
    "Cuddle Bunny",
    "Cheese Ball",
    "Doll Face",
    "Princess",
    "Princess Peach",
    "Lover Girl",
    "Love Bug",
    "My Queen",
    "Queenie",
    "Kitty",
    "Miss Kitty",
    "Kitty Cat",
    "Boo",
    "Boo Bear",
    "Meow",
    "Little Monkey",
    "Tea Cup",
    "Cute Mama",
    "Teddy Bear",
    "Fluffy",
    "Dimples",
    "Baby Cakes",
    "Baby Boo",
    "Darling",
    "Freckles",
    "Cute Face",
    "Giggly",
    "Snuggle Bug",
    "My All",
    "Button",
    "Babe",
    "Baby",
    "Baby Doll",
    "Baby Girl",
    "Babelicious",
    "Smiley Face",
    "Bubble Gum",
    "Double Bubble",
    "Bite-Size",
    "Fun-Size",
    "Pocket-Size",
    "Bunny Ears",
    "Fine Wine",
    "Sugar Lips",
    "Chipmunk",
    "Skippy",
    "Smarty Pants",
    "Smiles",
    "Snuggly Bear",
    "Snugglebear",
    "Nibbles",
    "Pickle",
    "Baby Carrot",
    "Sweet Pea",
    "Berry",
    "Berry Boo",
    "Tangerine",
    "Kiwi",
    "Cuckoo",
    "Birdie",
    "Little Otter",
    "Lil´ Mouse",
    "Buzzy Bee",
    "Ladybug",
    "Munchie",
    "Rum-Rum",
    "Picklehead",
    "Little Peanut",
    "Bambi",
    "Cherry Blossom",
    "Passion Fruit",
    "Snappy",
    "Pinky",
    "Num Nums",
    "Luv",
    "Luv Puppies",
    "Little Mama",
    "Kissy Face",
    "Fluffernutter",
    "Duckling",
    "Bee’s Knees",
    "Beanie",
    "Lovebird",
    "Baby Boo",
    "Cute Eyes",
    "Lil Dove",
    "Little Dove",
    "Daisy",
    "Tulip",
    "Rose",
    "Angel Eyes",
    "Wifey",
    "Precious",
    "Treasure",
    "Sunshine",
    "Sunny",
    "Beautiful",
    "Gorgeous",
    "Butterfly",
    "Cinderella",
    "Amore",
    "Dove",
    "Bella",
    "Angel",
    "Angel Face",
    "Angel of Mine",
    "Cherubie",
    "D-Vine",
    "Poppy Seed",
    "Heaven-Sent",
    "Angelita",
    "Angel Wing",
    "Angel Baby",
    "Chica",
    "Gorgeous",
    "Gumdrop",
    "Jewl",
    "Jewel",
    "One & Only",
    "Bright Eyes",
    "Blue Eyes",
    "Brown Eyes",
    "Green Eyes",
    "Light of My Soul",
    "Lovebird",
    "My Fair Lady",
    "Sparkly Eyes",
    "Sun Beams",
    "Moon Beams",
    "Little Flower",
    "Frostie",
    "Dreamy",
    "Little Heart",
    "Sunflower",
    "Sunny",
    "Star Shine",
    "Cloudy Eyes",
    "Milady",
    "My Lady",
    "Emerald",
    "Gorgeous Girl",
    "Rosebud",
    "Valentine",
    "Poppy",
    "Bluebell",
    "Dear",
    "Dearest",
    "Beloved",
    "Charming",
    "Angeleto",
    "Soulmate",
    "Peach Blossom",
    "Dreamweaver",
    "Heart Stopper",
    "Pearl",
    "Perfection",
    "Snowflake"
  ];
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        //USED TO CREATE THE PAGE
        appBar: AppBar(
          //THE UPPER NAV BAR
          title: Text(
            "GOODMORNING SANSKRITI",
          ),
        ),
        body: Column(
          children: <Widget>[
            RaisedButton(
                child: Text("CLICK      ME"),
                color: Color(50),
                onPressed: () {
                  setState(() {});
                }),
            Card(
              child: _myphoto[rng.nextInt(27)],
            ),
            Text(
              _product[rng.nextInt(247)],
              style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
            )
          ],
        ), //BODY IS ALL THE WHITE SPACE BELOW THE BLUE REGION
      ),
    );
  }
}
